Apparently pyasn can not determine for all IPs the ASN.
	ERROR IntegrityError: failed attempt to insert ('butt-head.ru', '91.201.202.106', None)
	ERROR IntegrityError: failed attempt to insert ('penguins.pl', '91.228.199.142', None)